accent = "#e2462f"
cursor = "#4e4750"
foreground = "#4e4750"
background = "#f6f2ee"
selection_foreground = "#4e4750"
selection_background = "#e7d2be"

color0 = "#c8bdb2"
color1 = "#a5222f"
color2 = "#396847"
color3 = "#ac5402"
color4 = "#2848a9"
color5 = "#6e33ce"
color6 = "#287980"
color7 = "#f2e9e1"
color8 = "#9c8c80"
color9 = "#b3434e"
color10 = "#577f63"
color11 = "#b86e28"
color12 = "#4863b6"
color13 = "#8452d5"
color14 = "#488d93"
color15 = "#f4ece6"
