mode = "light"

accent = "#b30000"
selection = "#f2ddda"
muted = "#726f6c"

background = "#f7f3f1"
dark_background = "#f3ece7"
darker_background = "#eae2dd"
lighter_background = "#faf9f7"

foreground = "#3a3430"
dark_foreground = "#726f6c"
light_foreground = "#57524f"
bright_foreground = "#2d2928"

red = "#b30000"
yellow = "#9b5139"
orange = "#c9271e"
green = "#396847"
cyan = "#287980"
blue = "#205ea6"
magenta = "#a26958"
brown = "#7a0000"

bright_red = "#c9271e"
bright_yellow = "#d5a670"
bright_green = "#577f63"
bright_cyan = "#488d93"
bright_blue = "#4385be"
bright_magenta = "#cf5f5c"
