# RubyLLM Light colors for Ghostty

background = #f6f2ee
foreground = #4e4750
selection-background = #e7d2be
selection-foreground = #4e4750
cursor-color = #4e4750

# normal
palette = 0=#c8bdb2
palette = 1=#a5222f
palette = 2=#396847
palette = 3=#ac5402
palette = 4=#2848a9
palette = 5=#6e33ce
palette = 6=#287980
palette = 7=#f2e9e1

# bright
palette = 8=#9c8c80
palette = 9=#b54230
palette = 10=#577f63
palette = 11=#b86e28
palette = 12=#4863b6
palette = 13=#8452d5
palette = 14=#488d93
palette = 15=#f4ece6

# extended colors
palette = 16=#8a6840
palette = 17=#a440b5
