# RubyLLM Light colors for Ghostty

background = #f7f3f1
foreground = #3a3430
selection-background = #f2ddda
selection-foreground = #3a3430
cursor-color = #3a3430

# normal
palette = 0=#d4d0cd
palette = 1=#b30000
palette = 2=#396847
palette = 3=#9b5139
palette = 4=#205ea6
palette = 5=#a26958
palette = 6=#287980
palette = 7=#57524f

# bright
palette = 8=#726f6c
palette = 9=#c9271e
palette = 10=#577f63
palette = 11=#d5a670
palette = 12=#4385be
palette = 13=#cf5f5c
palette = 14=#488d93
palette = 15=#3a3430

# extended colors
palette = 16=#d5a670
palette = 17=#db9894
