# RubyLLM Light colors for Kitty

background #f7f3f1
foreground #3a3430
selection_background #f2ddda
selection_foreground #3a3430
cursor_text_color #f7f3f1
url_color #b30000

# Cursor
# uncomment for reverse background
# cursor none
cursor #3a3430

# Border
active_border_color #b30000
inactive_border_color #d4d0cd
bell_border_color #c9271e

# Tabs
active_tab_background #b30000
active_tab_foreground #faf9f7
inactive_tab_background #f2ddda
inactive_tab_foreground #726f6c

# normal
color0 #d4d0cd
color1 #b30000
color2 #396847
color3 #9b5139
color4 #205ea6
color5 #a26958
color6 #287980
color7 #57524f

# bright
color8 #726f6c
color9 #c9271e
color10 #577f63
color11 #d5a670
color12 #4385be
color13 #cf5f5c
color14 #488d93
color15 #3a3430

# extended colors
color16 #d5a670
color17 #db9894
